# Generated by Django 3.1.6 on 2021-02-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210223_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
